openapi: 3.1.0
info:
  title: VEKA examen API
  description: Rest API services examen van het Vlaams Energie- en Klimaatagentschap
  contact:
    name: VEKA
    url: https://www.energiesparen.be
    email: veka@vlaanderen.be
  license:
    name: European Union Public Licence (EUPL)
    url: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12
  version: "v1"
servers:
  - url: https://energie-ti-secure.api.vlaanderen.be
tags:
  - name: Examen controller
    description: Examens
paths:
  /examens-api/v1/examendagen/{examendagId}:
    put:
      tags:
        - Examen controller
      description: Wijzig een examendag op basis van examendag id.
      operationId: wijzigExamendag
      parameters:
        - name: examendagId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutExamendagInputRestDto"
        required: true
      responses:
        "200":
          description: OK
  /examens-api/v1/examens/{examenId}/resultaten:
    post:
      tags:
        - Examen controller
      description: Examen resultaten toevoegen voor een examen
      operationId: postExamenResultaten
      parameters:
        - name: examenId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/PostExamenResultatenInputRestDto"
              uniqueItems: true
        required: true
      responses:
        "201":
          description: Het object is aangemaakt.
        "400":
          description: Ongeldige request
          content:
            application/json:
              schema:
                example:
                  errors:
                    - detail: Minimaal param1 of param2 zijn verplicht.
                  detail: Er zijn één of meerdere validatie fouten opgetreden. Controleer
                    het errors attribuut voor meer informatie.
                  status: 400
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.4.1
                  path: /voorbeeld-api/voorbeeld-endpoint
                  title: Bad Request
                  timestamp: 2024-09-02T15:03:37.449+02:00
        "403":
          description: Forbidden
        "500":
          description: Er is een fout opgetreden.
          content:
            application/json:
              schema:
                example:
                  errors:
                    - errorCode: 12738bac-8707-4eb2-b746-a7b97e5723a4
                      detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  status: 500
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.5.1
                  path: /voorbeeld-api/voorbeeld-endpoint/4d3930c8-8c75-433f-a9f1-7684e7cc5000
                  title: Internal Server Error
                  timestamp: 2024-09-03T15:03:37.449+02:00
  /examens-api/v1/examendagen:
    post:
      tags:
        - Examen controller
      description: Sla de registratie op van een nieuwe examendag.
      operationId: postExamendag
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostExamendagInputRestDto"
        required: true
      responses:
        "201":
          description: Het object is aangemaakt.
        "400":
          description: Ongeldige request
          content:
            application/json:
              schema:
                example:
                  errors:
                    - detail: Minimaal param1 of param2 zijn verplicht.
                  detail: Er zijn één of meerdere validatie fouten opgetreden. Controleer
                    het errors attribuut voor meer informatie.
                  status: 400
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.4.1
                  path: /voorbeeld-api/voorbeeld-endpoint
                  title: Bad Request
                  timestamp: 2024-09-02T15:03:37.449+02:00
        "403":
          description: Forbidden
        "500":
          description: Er is een fout opgetreden.
          content:
            application/json:
              schema:
                example:
                  errors:
                    - errorCode: 12738bac-8707-4eb2-b746-a7b97e5723a4
                      detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  status: 500
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.5.1
                  path: /voorbeeld-api/voorbeeld-endpoint/4d3930c8-8c75-433f-a9f1-7684e7cc5000
                  title: Internal Server Error
                  timestamp: 2024-09-03T15:03:37.449+02:00
  /examens-api/v1/examendagen/{examendagId}/examens:
    post:
      tags:
        - Examen controller
      description: Sla een examen op voor een specifieke examendag.
      operationId: postExamen
      parameters:
        - name: examendagId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostExamenInputRestDto"
        required: true
      responses:
        "201":
          description: Het object is aangemaakt.
        "400":
          description: Ongeldige request
          content:
            application/json:
              schema:
                example:
                  errors:
                    - detail: Minimaal param1 of param2 zijn verplicht.
                  detail: Er zijn één of meerdere validatie fouten opgetreden. Controleer
                    het errors attribuut voor meer informatie.
                  status: 400
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.4.1
                  path: /voorbeeld-api/voorbeeld-endpoint
                  title: Bad Request
                  timestamp: 2024-09-02T15:03:37.449+02:00
        "403":
          description: Forbidden
        "500":
          description: Er is een fout opgetreden.
          content:
            application/json:
              schema:
                example:
                  errors:
                    - errorCode: 12738bac-8707-4eb2-b746-a7b97e5723a4
                      detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  status: 500
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.5.1
                  path: /voorbeeld-api/voorbeeld-endpoint/4d3930c8-8c75-433f-a9f1-7684e7cc5000
                  title: Internal Server Error
                  timestamp: 2024-09-03T15:03:37.449+02:00
  /examens-api/v1/examens:
    get:
      tags:
        - Examen controller
      description: Geef alle examens op basis van criteria terug.
      operationId: getExamens
      parameters:
        - name: examenRequestDto
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/ExamenRequestDto"
      responses:
        "200":
          description: OK
        "204":
          description: Geen data om terug te geven.
        "404":
          description: Er zijn geen gegevens gevonden.
          content:
            application/json:
              schema:
                example:
                  errors:
                    - detail: Resource niet gevonden
                  detail: Resource not found
                  status: 404
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.4.5
                  path: /voorbeeld-api/voorbeeld-endpoint/4d3930c8-8c75-433f-a9f1-7684e7cc5000
                  title: Not Found
                  timestamp: 2024-09-04T15:03:37.449+02:00
        "400":
          description: Ongeldige request
          content:
            application/json:
              schema:
                example:
                  errors:
                    - detail: Minimaal param1 of param2 zijn verplicht.
                  detail: Er zijn één of meerdere validatie fouten opgetreden. Controleer
                    het errors attribuut voor meer informatie.
                  status: 400
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.4.1
                  path: /voorbeeld-api/voorbeeld-endpoint
                  title: Bad Request
                  timestamp: 2024-09-02T15:03:37.449+02:00
        "403":
          description: Forbidden
        "500":
          description: Er is een fout opgetreden.
          content:
            application/json:
              schema:
                example:
                  errors:
                    - errorCode: 12738bac-8707-4eb2-b746-a7b97e5723a4
                      detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  status: 500
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.5.1
                  path: /voorbeeld-api/voorbeeld-endpoint/4d3930c8-8c75-433f-a9f1-7684e7cc5000
                  title: Internal Server Error
                  timestamp: 2024-09-03T15:03:37.449+02:00
  /examens-api/v1/examens/{id}/inschrijvingen:
    get:
      tags:
        - Examen controller
      description: Ingeschreven personen op een examen.
      operationId: getInschrijvingenEnergiedeskundigeTypeD
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "204":
          description: Geen data om terug te geven.
        "404":
          description: Er zijn geen gegevens gevonden.
          content:
            application/json:
              schema:
                example:
                  errors:
                    - detail: Resource niet gevonden
                  detail: Resource not found
                  status: 404
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.4.5
                  path: /voorbeeld-api/voorbeeld-endpoint/4d3930c8-8c75-433f-a9f1-7684e7cc5000
                  title: Not Found
                  timestamp: 2024-09-04T15:03:37.449+02:00
        "400":
          description: Ongeldige request
          content:
            application/json:
              schema:
                example:
                  errors:
                    - detail: Minimaal param1 of param2 zijn verplicht.
                  detail: Er zijn één of meerdere validatie fouten opgetreden. Controleer
                    het errors attribuut voor meer informatie.
                  status: 400
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.4.1
                  path: /voorbeeld-api/voorbeeld-endpoint
                  title: Bad Request
                  timestamp: 2024-09-02T15:03:37.449+02:00
        "403":
          description: Forbidden
        "500":
          description: Er is een fout opgetreden.
          content:
            application/json:
              schema:
                example:
                  errors:
                    - errorCode: 12738bac-8707-4eb2-b746-a7b97e5723a4
                      detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  status: 500
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.5.1
                  path: /voorbeeld-api/voorbeeld-endpoint/4d3930c8-8c75-433f-a9f1-7684e7cc5000
                  title: Internal Server Error
                  timestamp: 2024-09-03T15:03:37.449+02:00
  /examens-api/v1/examendagen/{examendagId}/examens/{examenId}:
    delete:
      tags:
        - Examen controller
      description: Verwijder een examen op basis van examendag id en examen id.
      operationId: verwijderExamen
      parameters:
        - name: examendagId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: examenId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: No Content
components:
  schemas:
    CentrumAdres:
      type: object
      properties:
        straat:
          type: string
        huisnummer:
          type: string
        busNummer:
          type: string
        postcode:
          type: string
        gemeente:
          type: string
        land:
          type: string
      required:
        - gemeente
        - huisnummer
        - land
        - postcode
        - straat
    PutExamendagInputRestDto:
      type: object
      properties:
        examendagId:
          type: integer
          format: int64
        datum:
          type: string
          format: date
        uur:
          type: string
          pattern: "^(2[0-3]|[01]?\\d):([0-5]?\\d)$"
        centrumNaam:
          type: string
        centrumAdres:
          $ref: "#/components/schemas/CentrumAdres"
        maxAantalDeelnemers:
          type: integer
          format: int32
          minimum: 1
        uitersteInschrijvingsdatum:
          type: string
          format: date
        verborgen:
          type: boolean
      required:
        - centrumAdres
        - centrumNaam
        - datum
        - examendagId
        - uitersteInschrijvingsdatum
        - uur
    PostDeelResultaat:
      type: object
      properties:
        deelNaam:
          type: string
        deelPercentage:
          type: number
          format: double
    PostExamenResultatenInputRestDto:
      type: object
      properties:
        rijksregisternummer:
          type: string
        totaalPercentage:
          type: number
          format: double
        deelResultaten:
          type: array
          items:
            $ref: "#/components/schemas/PostDeelResultaat"
        isGeslaagd:
          type: boolean
    PostExamendagInputRestDto:
      type: object
      properties:
        examendagId:
          type: integer
          format: int64
        datum:
          type: string
          format: date
        uur:
          type: string
          pattern: "^(2[0-3]|[01]?\\d):([0-5]?\\d)$"
        centrumNaam:
          type: string
        centrumAdres:
          $ref: "#/components/schemas/CentrumAdres"
        maxAantalDeelnemers:
          type: integer
          format: int32
          minimum: 1
        uitersteInschrijvingsdatum:
          type: string
          format: date
        verborgen:
          type: boolean
      required:
        - centrumAdres
        - centrumNaam
        - datum
        - examendagId
        - uitersteInschrijvingsdatum
        - uur
    PostExamenInputRestDto:
      type: object
      properties:
        examenId:
          type: integer
          format: int64
        registratieRol:
          type: string
        examenType:
          type: string
      required:
        - examenId
        - examenType
        - registratieRol
    ExamenRequestDto:
      type: object
      properties:
        registratieRol:
          type: string
        examenType:
          type: string
        examenDatumVan:
          type: string
          format: date
        examenDatumTot:
          type: string
          format: date
        isVerborgen:
          type: boolean
        examendagId:
          type: integer
          format: int64
